### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by Tongxuan259** [luhr2003/UniGarmentManip#3]
Hi, thanks for releasing the code of this great work. Since I have encountered problems with environment setup. I am wondering if it is possible to realse a dockerfile?

**Comment by warshallrho** [comment]
After an discussion with @luhr2003 , we think you can try pulling the dockerfile of https://github.com/Xingyu-Lin/softgym to ensure a plausible environment, and then compile our code in this environment.

**Comment by Tongxuan259** [comment]
Hi Ruihai,

Thanks for the quick response. I have tried the docker image provided by
softgym and it works well. Thanks for your help.

Best,
Tongxuan

**Comment by Tongxuan259** [comment]
Hi I am curious if you have did any modification to PyFleX because I noticed some api like` pyflex.empty` and `pyflex.add_cloth_mesh` can't be found when I use the PyFlex from softgym.
